---
version: "3"
services:
  dth:
    image: durgalijja/dth:v1
    ports:
      - 8007:80
    volumes:
      - volume1
    deploy:
      replicas: 4
  train:
    image: durgalijja/train:v1
    volumes:
      - volume2
    ports:
      - 8008:80
    deploy:
      replicas: 4
  recharge:
    image: durgalijja/recharge:v1
    volumes:
      - volume3
    ports:
      - 8009:80
    deploy:
      replicas: 4
